### ISSUE TITLE
An apology from me

### ISSUE THREAD

**Issue by DARKDRAGON532** [NC22/KellyC-Show-YouTube-Dislikes#1]
Hey Kelly,
I would like to apologise on behalf of all people who brigaded your extension. Brigading isn't nice to do and we should've communicated to you peacefully.

The reason the community was upset was because you were aware of the extension "Return YouTube Dislike", because you used the API in the source code, and still decided to copy the name, and you didn't even credit for the API.
In response to this we shouldn't have brigaded your extension.

Though you deleting your commit history and trying to erase any mention of the API from the source code wasn't a good move. Please don't try to deny you didn't use the API, I had looked through your source code and you used it as a fallback. Though a little attribution in the README would've been valued more, and maybe coming up with an original name too, because trust me, there are thousands of better names to choose from.

I won't be blaming you for your actions since I would've done the same when under pressure due to the brigading.

I hope you understand this, you don't need to change your extension name, and feel free to use the API again (with some attribution), but I hope you learn from this mistake, because at least we are.

**Comment by NC22** [comment]
Hi. Thank you for response

sad that author wasnt interested in conversation from begining. Instead of spam Dmitry could also start from create an issue about copyrights here \ email me letter \ collect some prove data from github \ suggest some improvements...at least try to ask something, i usually reply not very long. But yes, he just started from spam and then blaming why I started to update \ relocate something so fast

> Please don't try to deny you didn't use the API, I had looked through your source code and you used it as a fallback. 

I not deny that. I mentioned that in conversation https://catface.ru/userfiles/media/udata_1638058127_nyrrlltj.png There is some implementation of display source already in KellyC RYD but maybe its will look not so clear for user what data he gets (this notice will shown in sentiment bar popup and currently implementation is partly cuted)
Also at a time Dmitry start spaming attack - extension already not used his api even as alternative - version 1.1.1.2 - only mention in manifest (update manifest always takes 3-4 days in extension store), but its not affects on anything. 

> I hope you understand this, you don't need to change your extension name, and feel free to use the API again (with some attribution), but I hope you learn from this mistake, because at least we are.

I'll try to add my prefix KellyC for extension name or rename \ recreate if spam continued, but its still actions that usually require much more time from Chrome Extension Store Moderation to approve. 

Any way again big thank you found time to write here!

**Comment by DARKDRAGON532** [comment]
> I'm not denying that. I mentioned that in conversation https://catface.ru/userfiles/media/udata_1638058127_nyrrlltj.png

I'm sorry, I never saw that response. But it's okay now.

> current version 1.1.1.2 works without unauthored apis, I'll add list of APIs and links to original projects to Readme \ description \ and some optional notices in popup sentiment section if I bring it back in some way. If you \ author (?) allow that

That seems cool, I remember Dmitri saying that it's fine if you used his API, but I'm not sure, feel free to open an issue on github to ask if you ever wish to, or let me know, I can ask him myself.

> Ok Thank you. I already sended earlier some changes - wanted to add prefix "KellyC", but this type of updates takes time for chrome ex. moderators
I know, it took us two days to get the logo updated.

> Any way again big thank you found time to write here!
No problem, I'll send an announcement in the discord to tell everyone to remove their one star reviews if possible.

**Comment by NC22** [comment]
> This seems cool, I remember Dmitry said it was ok if you used his API, but I'm not sure, feel free to open a question on github to ask if you ever want to, or let me know I I can ask him myself.

Thanks. I added a link to the RYD project to the readme. I think it would be fair to say that it was used.

> I will post a discord ad to ask everyone to remove their one star reviews if possible.

Thanks. I can understand if Dmitry wont remove his review and conversation. Only thing that in some anwers he and few others appelate on false information (may be he wasnt clear enough that problem was in name \ api), tell that I just copypaste code. I cant accept that, and will keep my anwers too for this cases https://catface.ru/userfiles/media/udata_1638094890_pfcwjvyd.png

**Comment by DARKDRAGON532** [comment]
Fair, there was some misunderstanding here, I've requested them to remove the reviews if they are able to, hopefully everything is fine now

**Comment by Anarios** [comment]
Hi, wanted to join the apology. From my point of view (and rushed decision) it looked like you're sitting in our the discord channel (because your github repo history clean-up happened right after I wrote in discord), and instead of just writing "Hey guys, sorry, lets make this right" - silently deleting history.

To be clear - I never said  that your current extension is a copy-paste of my code. I even mentioned good code quality. But - exactly as I was looking through past commits and saw something familiar - the history got deleted. So I said "feels like at the start it was just a copy-paste, but now history is deleted, so not completely sure"

So yeah, this was a misjudgment by me, I deleted all my reviews and comments and asked others to do the same.


Good luck to you and your extension.

**Comment by NC22** [comment]
>   it looked like you're sitting in our the discord channel (because your github repo history clean-up happened right after I wrote in discord), and instead of just writing "Hey guys, sorry, lets make this right" - silently deleting history.

oh, may be. Before I reset github repository this already looked like some kind of brigade move. It wasnt just your response in reviews already at that moment. I not really familar with discord. I tried to register later (my nickname @nradiowave) to figureout where this started. There was some suggestions to open issue by DARKDRAGON532 before reviews to come https://discord.com/channels/909435648170160229/909435648665071660/914159619985776640 if I was there it really wasnt that hard to just response, but I found this thread very late

> So it looked like you used the API (so clearly knew about us), used the same name, and didn't even mention original project.

Yes, I understand. Sorry. 
Good luck

**Comment by NC22** [comment]
@Anarios @DARKDRAGON532 

> That seems cool, I remember Dmitri saying that it's fine if you used his API, but I'm not sure, feel free to open an issue on github to ask if you ever wish to, or let me know, I can ask him myself.

Hello. I reworked data providers controller for next version of my extension, so now it would be pretty clear for user, where data came from.

Example of how it looks \ all currently used APIs listed in readme.  Will be listed in description too

https://github.com/NC22/KellyC-Return-YouTube-Dislikes

Optionaly requests for counting user actions (like \ dislike) for any driver can be implemented via callbacks. As I understand current version of API not support actions, so I disable this function for ryda driver for now. When this features be ready, I'll recheck out.

Every api driver in options listed with description \ home page of project

Return Youtube Dislike API driver description can be found here :

https://github.com/NC22/KellyC-Return-YouTube-Dislikes/blob/main/lib/api/ryda.js
https://github.com/NC22/KellyC-Return-YouTube-Dislikes/blob/main/_locales/en/messages.json#L39
https://github.com/NC22/KellyC-Return-YouTube-Dislikes/blob/main/_locales/ru/messages.json#L45

If this variant of credits is acceptable I'll include ryda controller to next prod version.

**Comment by DARKDRAGON532** [comment]
> Optionaly requests for counting user actions (like \ dislike) for any driver can be implemented via callbacks. As I understand current version of API not support actions, so I disable this function for ryda driver for now. When this features be ready, I'll recheck out.

We will be implementing some authentication for sending like/dislike data so not sure how you would be able to implement that into your own extension.

> If this variant of credits is acceptable I'll include ryda controller to next prod version.

it seems fine to me, but you should wait for Anarios' response.

**Comment by NC22** [comment]
> We will be implementing some authentication for sending like/dislike data so not sure how you would be able to implement that into your own extension

interesting. For example SponsorBlock uses sha256 hash as userId and then identify actions by that id \ limit some requests from server side. Also all data is unpersonalized during requests (videoId \ userid) because of hash. 

https://github.com/NC22/KellyC-Return-YouTube-Dislikes/blob/main/lib/api/sponsorBlock.js#L61

but of course, may be it needs more complex system in your case

**Comment by Anarios** [comment]
> If this variant of credits is acceptable I'll include ryda controller to next prod version.

Looks nice to me, I'll update you once our API starts accepting user votes, currently post methods are just a placeholder.

**Comment by DARKDRAGON532** [comment]
We're accepting user votes, unfortunately there arent any formal documentation but you can read the content and background script and understand how to do it

**Comment by NC22** [comment]
@ DARKDRAGON532

thanks, already added implementation few days ago according to Anarios source code, still testing how quickly votes are added to cached data after vote requests, but overall the voting actions \ registration is accepted without any issues and works fine. I keeped same behaviour, so registration called only once per user, then just calls on vote actions. https://github.com/NC22/KellyC-Return-YouTube-Dislikes/blob/main/extension/lib/api/ryda.js

**Comment by NC22** [comment]
@Anarios

Здравствуйте. Пару дней стал наблюдать, что с некоторых провайдеров (конкретно у меня Ростелеком) из РФ стал пропадать доступ к сайтам без явной отметки в списках блокировок Роскомнадзора. Исключением не стало и API https://returnyoutubedislikeapi.com/ запросы проходят не всегда. Мб у сервиса появились какие-либо зеркала \ сервисы-бекапы баз данных за это время или проект все еще закрытый? Пока единственный комфортный для себя вариант нашел, использовать свой сервер (https://catface.ru/) в качестве сервера кеширования для returnyoutubedislikeapi т.к. доступ к хосту с него все еще есть.

Сделал кеш на запросы по 350 минут для каждого видео, запросы на returnyoutubedislikeapi идут только если человек использует локаль Ru чтобы исключить лишний трафик. Текущая реализация бека - https://catface.ru/userfiles/media/udata_1650702417_qyjsbiuy.zip

Пока использую персонально в своих целях без привязки к рабочей версии расширения.
Можно ли добавить этот "ретранслятор" себе в расширение в качестве альтернативного источника или возможно у вас есть какие-то более надежные решения для альтернативных подключений ?

**Comment by Anarios** [comment]
>  без явной отметки в списках блокировок Роскомнадзора

 У нас cloudflare, и их айпишники порой ловят бан от Роскомпозора, из-за того что соседствуют с запрещёнными сайтами :(
 
 Ничего против кэширующего прокси не имею, наборот - даже за. Начнёшь упираться в лимит запросов (429-е respons-ы появятся) - пиши, подниму лимит.
 
 "или возможно у вас есть какие-то более надежные решения для альтернативных подключений"  - планирую добавить несколько зеркал. Отпишусь как сделаю

**Comment by NC22** [comment]
@Anarios понял, спасибо !
