### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by icecream1812** [NC22/KellyC-Show-YouTube-Dislikes#16]
The extension is not working. It's not letting me see the dislikes on Youtube.

**Comment by NC22** [comment]
Hi. Thank you for inform. Desktop issues for new layout fixed in version 1.1.5.8. Problem is Chrome \ Edge extension store moderation takes 4-5 days after upload. So wait until version update 4-5 days, or use FF version - https://addons.mozilla.org/ru/firefox/addon/return-youtube-dislike/ or use version from github (install current version - https://github.com/NC22/KellyC-Show-YouTube-Dislikes/archive/refs/heads/main.zip manually in developer mode)
